config/routes.rb
Stagecraft::Application.routes.draw do
  get "welcome/index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :instances do
    member do
      get 'travel/:gateway_id' => 'instances#travel', as: :travel
      get 'converse/:appearance_id' => 'instances#converse', as: :converse
      get 'interact/:item_id' => 'instances#interact', as: :interact
    end
  end

  root 'welcome#index'

end

app/models/action.rb
class Action < ActiveRecord::Base
  include Tokenable

  belongs_to :variable
  belongs_to :item
  belongs_to :gateway
  belongs_to :appearance
  belongs_to :dialogue
end

app/models/appearance.rb
class Appearance < ActiveRecord::Base
  include Tokenable

  belongs_to :character
  belongs_to :scene
  has_many :dialogues
  has_many :rules
  has_many :events
end

app/models/character.rb
class Character < ActiveRecord::Base
  include Tokenable

  belongs_to :game
  has_many :appearances
  has_many :scenes, :through => :appearances
  has_many :dialogues, :through => :appearances
  has_many :rules, :through => :appearances
  has_many :events, :through => :appearances
end

app/models/concerns/eventable.rb
module Eventable
  extend ActiveSupport::Concern

  included do
  end

  def run_events(instance)
    self.events.each do |event|
      instance.instance_variables.where(variable_id: event.variable_id).first_or_create! do |iv|
        iv.value = event.value
      end
    end
  end
end

app/models/concerns/rulable.rb
module Rulable
  extend ActiveSupport::Concern

  def available?(instance)
    self.rules.each do |rule|
      iv = instance.instance_variables.find_by(:variable_id => rule.variable_id)
      if iv == nil || (rule.variable_id == iv.variable_id && rule.value != iv.value)
        return false
      end
    end
    return true
  end
end

app/models/dialogue.rb
class Dialogue < ActiveRecord::Base
  include Tokenable

  belongs_to :appearance
  has_many :rules
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  include Tokenable

  belongs_to :variable
  belongs_to :item
  belongs_to :gateway
  belongs_to :appearance
  belongs_to :dialogue
end

app/models/game.rb
class Game < ActiveRecord::Base
  include Tokenable

  has_many :scenes
  belongs_to :first_scene, :class_name => "Scene", :foreign_key => :first_scene_id
end

app/models/gateway.rb
class Gateway < ActiveRecord::Base
  include Tokenable
  include Rulable
  include Eventable

  belongs_to :source_scene, :class_name => "Scene", :foreign_key => :source_scene_id
  belongs_to :destination_scene, :class_name => "Scene", :foreign_key => :destination_scene_id
  has_many :rules
  has_many :events

  def to_s
    "#{source_scene} -> #{destination_scene}"
  end

  alias_method :name, :to_s
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  include Tokenable

  belongs_to :player
  belongs_to :game
  has_many :instance_variables
  has_many :variable, :through => :instance_variables
  belongs_to :current_scene, :class_name => "Scene", :foreign_key => :current_scene_id
end

app/models/instance_variable.rb
class InstanceVariable < ActiveRecord::Base
  include Tokenable

  belongs_to :instance
  belongs_to :variable

  def to_s
    "#{variable}: #{value}"
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  include Tokenable
  include Eventable

  belongs_to :scene
  has_many :rules
  has_many :events

  def to_s
    "#{name}"
  end
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  include Tokenable

  belongs_to :player
  belongs_to :game
end

app/models/player.rb
class Player < ActiveRecord::Base
  include Tokenable

  has_many :instances
  has_many :ownerships
  has_many :games, :through => :ownerships
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  include Tokenable

  belongs_to :variable
  belongs_to :item
  belongs_to :gateway
  belongs_to :appearance
  belongs_to :dialogue
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  include Tokenable

  belongs_to :game
  has_many :items
  has_many :exits, :class_name => "Gateway", :foreign_key => :source_scene_id
  has_many :entrances, :class_name => "Gateway", :foreign_key => :destination_scene_id

  validates_presence_of :game_id

  def to_s
    "#{name}"
  end
end

app/models/variable.rb
class Variable < ActiveRecord::Base
  include Tokenable

  belongs_to :game
  has_many :rules
  has_many :events

  def to_s
    "#{name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :load_instance

  def show
  end

  # Scene actions

  def travel
    gateway = @instance.current_scene.exits.find(params[:gateway_id])
    @instance.current_scene = gateway.destination_scene
    @instance.save
    redirect_to instance_path(@instance)
  end

  def converse
  end

  def interact
    item = @instance.current_scene.items.find(params[:item_id])
    item.run_events(@instance)
    redirect_to instance_path(@instance)
  end

  private

  def load_instance
    @instance = Instance.find(params[:id]) if params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/instances/show.html.erb
<h1 class="page-header"><%= @instance.game.name %></h1>

<div class="row">
	<div class="col-md-9">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading"><h3 class="panel-title"><%= @instance.current_scene %></h3></div>
					<div class="panel-body">
						<%= @instance.current_scene.description %>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading">Items</div>
					<% if !@instance.current_scene.items.blank? %>
					<ul class="list-group">
						<% for item in @instance.current_scene.items %>
						<li class="list-group-item"><%= link_to item, interact_instance_path(:item_id => item.id) %></li>
						<% end %>
					</ul>
					<% else %>
					<div class="panel-body">
						The scene contains no items ... or does it?
					</div>
					<% end %>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading">Exits</div>
					<% if !@instance.current_scene.exits.blank? %>
					<ul class="list-group">
						<% for exit in @instance.current_scene.exits %>
						<% if exit.available?(@instance) %>
						<li class="list-group-item"><%= link_to exit, travel_instance_path(:gateway_id => exit.id) %></li>
						<% else %>
						<li class="list-group-item"><i class="glyphicon glyphicon-lock"></i> <%= exit %></li>
						<% end %>
						<% end %>
					</ul>
					<% else %>
					<div class="panel-body">
						The scene contains no exits ... is it foamy?
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-heading">Environment</div>
			<% if !@instance.instance_variables.blank? %>
			<ul class="list-group">
				<% for variable in @instance.instance_variables %>
				<li class="list-group-item"><%= variable %></li>
				<% end %>
			</ul>
			<% else %>
			<div class="panel-body">
				It smells a bit funny ... that's it ... I swear!
			</div>
			<% end %>
		</div>
	</div>
</div>